version: '3'
services:
  build-app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms: 
        - "linux/amd64"
        - "linux/arm64"
        - "linux/arm64/v8"
    image: "mmhk/motors-backup"


  app:
    image: "mmhk/motors-backup"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    command: ["motors-backup", "your_table"]